INSERT INTO supplier (supplier_name, supplier_description, supplier_rating, supplier_image_path)
VALUES('Restaurant Depot', 'Big, expensive restaurant store', '3', ''), 
      ('Abrams Tanks R Us', 'Finest tanks this side of the Berlin Wall', '5', ''),
      ('Lagunitas', 'Chicago Beers, the good kind', '5', ''),
      ('Ben & Ben Co', 'Chicago''s finest hot sauce', '5', ''),
      ('Apple', 'Expensive hardware', '4', ''),
      ('Tooth Fairy', 'Scam, rip-off, doesn''t scale with inflation', '1', '');


INSERT INTO product (product_name, product_description, product_image_path)
VALUES('Abrams Tank', '', ''), 
      ('B-52 Bomber', '', ''),
      ('Lagunitas Sterohopic IPA', '', ''),
      ('Hullabalooberry', '', ''),
      ('Ben Dibuz', '', ''),
      ('iPhone 13', '', ''),
      ('Two Front Teeth', '', ''),
      ('Special Keyboard', '', ''),
      ('Glow in the Dark Anus', '', ''),
      ('Expensive Doormat', '', '');

INSERT INTO materials (material_name, material_description, material_image_path)
VALUES('Scrap Metal', '', ''), 
      ('Hops', '', ''),
      ('Aluminum', '', ''),
      ('Silicon', '', ''),
      ('Water', '', ''),
      ('Enamel', '', ''),
      ('Keratin', '', ''),
      ('Anus', '', '');